name: ci
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache bigger downloads
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

      # Separate cache for build dir, we reuse it in release publish workflow
      - name: Cache build output
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/cache@v2
        id: build-cache
        with:
          path: dist
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.sha }}

      - name: Confirm build works
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: npm run build

      # Persist produced build dir:
      # - this is not for releases, but for quick testing during the dev
      # - action artifacts can be downloaded for 90 days, then are removed by github
      - name: Attach produced build to Github Action
        uses: actions/upload-artifact@v2
        with:
          name: saturn-webui_${{ github.sha }}
          path: dist
          if-no-files-found: error

  test-unit:
    name: 'test:unit'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache bigger downloads
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

      - name: Run unit tests
        run: npm run test:unit

  test-e2e:
    name: 'test:e2e'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache bigger downloads
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: saturn-webui_${{ github.sha }}
          path: dist

      - name: Run E2E tests
        run: npm run test:e2e

  # separate check for TS
  typecheck:
    name: typecheck
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache bigger downloads
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

      - name: Fancy Typecheck with GH annotations
        uses: gozala/typescript-error-reporter-action@v1.0.8
        with:
          project: tsconfig.json

      # make sure local check is also ok
      - name: Userland check
        run: npm run typecheck

  # separate check for eslint
  eslint:
    name: eslint
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Cache bigger downloads
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/.cache
          key: ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('package.json', 'package-lock.json') }}
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm

      - name: ESLint
        run: npm run eslint

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    name: release
    needs: [build, test-unit, test-e2e, typecheck, eslint]
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_GITHUB_CI_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_GITHUB_CI_AWS_SECRET_ACCESS_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.PROD_AWS_ACCOUNT_NUMBER }}
      AWS_REGION: us-west-2
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Reuse tag build
      - name: Cache build dir
        uses: actions/cache@v2
        id: build-cache
        with:
          path: dist
          key: ${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ github.sha }}

      - name: Install and Build 🔧
        if: steps.build-cache.outputs.cache-hit != 'true'
        run: |
          npm ci --prefer-offline --no-audit --progress=false --cache ${{ github.workspace }}/.cache/npm
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}

      - name: Push to S3
        env:
          BUCKET: filecoin-saturn
        run: |
          aws s3 cp dist/index.html s3://$BUCKET/index.html \
            --cache-control "no-cache" --only-show-errors

          aws s3 cp dist/assets s3://$BUCKET/webui/assets/ --recursive \
            --cache-control "public, max-age=2592000" --only-show-errors

      - name: Create archive
        run: |
          cd dist
          tar -czf ../saturn-webui.tar.gz *

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: saturn-webui.tar.gz
